on:
  push:
    branches:
      - main
    paths:
      - "*.go"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: main
      - name: "Setup go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.4
      - name: "Switch branch"
        run: |
          git switch -c dist
      - name: "Build executable"
        run: |
          for i in $(ls ./**/*.go); do
            basename="${i%.*}"
            go build -o $basename.exe $i
          done
      - name: "Change readme"
        run: |
          cat - <<EOF > README.md
          # Exe'd bat collection: dist

          Feel free to download and use this exe collection.
          These executables are licensed under the WTFPL.

          ## Paths
          | Executable | Path |
          | ---------- | ---- |
          EOF
      - name: "Add paths"
        run: |
          for i in $(ls ./**/*.exe); do
            go_content=$(cat "${i%.*}.go")
            path_line=$(sed -n "2p" <<< "$go_content")
            exe_path="${path_line#*path: }"
            echo "| $i | $exe_path |" >> README.md
          done
      - name: "Delete not needed files"
        run: |
          rm -rf ./.github
          rm -rf ./.gitignore
          rm -rf ./**/*.go
      - name: "Upload to GitHub"
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Build with GitHub Actions"
          git push origin dist --force